version: '3'
services:
    web:
        depends_on: 
            - zookeeper
        environment: 
            - ZOOKEEPER_URI=zookeeper:2181
        build: .
        ports:
            - "8081:8081"
        networks: 
            - web-company
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        hostname: zoo1
        volumes:
            - /home/phuc/zookeeper:/data
        ports:
            - 2181-2181
        networks: 
            - web-company 
networks: 
    web-company: